import express from 'express'; import cors from 'cors'; import multer from 'multer'; import dotenv from 'dotenv'; import path from 'path'; import { v4 as uuid } from 'uuid';
import { localUpload } from './services/UploadService.js'; import { analyzeSkin } from './services/SkinAIService.js'; import { recommend } from './services/RecommendationAgent.js'; import { renderTryOn, renderBatch } from './services/VTOService.js'; import { pool } from './db/pool.js';
import { refineOutfitRequest } from './services/ChatAgentService.js';
import { searchImages } from './integrations/shoppingSearchClient.js';
dotenv.config(); if (!pool) throw new Error('DATABASE_URL must be configured: persistence is required.');
const app=express(), upload=multer({dest:path.join(process.cwd(),'server','.tmp')}); app.use(cors()); app.use(express.json()); app.use('/uploads',express.static(path.join(process.cwd(),'server','uploads')));
const q=(sql,values)=>pool.query(sql,values); const token=req=>req.header('x-guest-token')||'demo-guest';
async function user(req){const guest=token(req);const {rows:[u]}=await q('INSERT INTO users (guest_token) VALUES ($1) ON CONFLICT (guest_token) DO UPDATE SET guest_token=EXCLUDED.guest_token RETURNING *',[guest]);return u;}
const mapResult=row=>({id:row.tryon_id,result_image_url:row.result_image_url,youcam_request_id:row.youcam_request_id,batch_number:row.batch_number,garment:{id:row.search_id,name:row.name,source_site:row.source_site,image_url:row.image_url,buy_url:row.buy_url,price:row.price,category:row.category,color:row.color}});
async function sessionFor(id,userId){const {rows:[s]}=await q('SELECT * FROM sessions WHERE id=$1 AND user_id=$2',[id,userId]);if(!s)throw new Error('Session not found.');return s;}
async function resultRows(sessionId){const {rows}=await q(`SELECT tr.id tryon_id,tr.result_image_url,tr.youcam_request_id,sr.id search_id,sr.name,sr.source_site,sr.image_url,sr.buy_url,sr.price,sr.category,sr.color,sr.batch_number FROM tryon_results tr JOIN search_results sr ON sr.id=tr.search_result_id WHERE tr.session_id=$1 ORDER BY sr.batch_number DESC,tr.created_at DESC`,[sessionId]);return rows.map(mapResult);}
async function createBatch(session,message='') { const {rows:[body]}=await q('SELECT * FROM uploads WHERE id=$1 AND user_id=$2',[session.body_upload_id,session.user_id]);if(!body)throw new Error('Body photo no longer exists.'); let {rows:[skin]}=await q('SELECT * FROM skin_profile WHERE upload_id=$1 ORDER BY created_at DESC LIMIT 1',[body.id]);if(!skin){const analyzed=await analyzeSkin(body.url);const saved=await q('INSERT INTO skin_profile (user_id,upload_id,undertone,tone_value,raw_response) VALUES ($1,$2,$3,$4,$5) RETURNING *',[session.user_id,body.id,analyzed.undertone,analyzed.tone_value,analyzed.raw_response]);skin=saved.rows[0];} const {rows:catalog}=await q('SELECT * FROM search_results WHERE session_id IS NULL ORDER BY rank'); const selected=recommend(catalog,session.occasion_text,`${session.description_text} ${message}`,skin.undertone,session.gender);const {rows:[next]}=await q('SELECT COALESCE(MAX(batch_number),0)+1 AS batch FROM search_results WHERE session_id=$1',[session.id]);const batch=next.batch;
// Use vto_image_url (white-background from SERP Images) when available — gives YouCam cleaner garment input
const vtoGarments=selected.map(p=>({...p,image_url:p.vto_image_url||p.image_url}));
const renders=await renderBatch(body.url,vtoGarments);const results=[]; for(let i=0;i<selected.length;i++){const p=selected[i], r=renders[i];const {rows:[snapshot]}=await q('INSERT INTO search_results (session_id,name,source_site,image_url,buy_url,price,category,color,gender,occasion_tags,rank,batch_number) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *',[session.id,p.name,p.source_site,p.image_url,p.buy_url,p.price,p.category,p.color,p.gender,p.occasion_tags,p.rank,batch]);const {rows:[tryon]}=await q('INSERT INTO tryon_results (session_id,search_result_id,body_upload_id,result_image_url,youcam_request_id) VALUES ($1,$2,$3,$4,$5) RETURNING *',[session.id,snapshot.id,body.id,r.result_image_url,r.youcam_request_id]);results.push(mapResult({...tryon,tryon_id:tryon.id,search_id:snapshot.id,...snapshot}));}return results;}
app.get('/api/health',async(_,res)=>{const {rows:[count]}=await q('SELECT COUNT(*)::int count FROM search_results WHERE session_id IS NULL');res.json({ok:true,catalog:count.count,mode:'postgresql persistence'});});

// Returns fresh white-background garment images from SERP for a given query.
// Costs 1 SERP credit, zero VTO credits. Used by the frontend to preview
// the actual garment image before (or instead of) running a full VTO.
app.get('/api/serp-image',async(req,res)=>{
  try{
    const q2=req.query.q?.trim();
    if(!q2)return res.status(400).json({error:'q query param required'});
    const limit=Math.min(parseInt(req.query.limit||'4',10),8);
    const images=await searchImages(`${q2} product flat lay white background`,limit);
    res.json({images,query:q2});
  }catch(e){res.status(502).json({error:e.message});}});
app.post('/api/upload',upload.single('file'),async(req,res)=>{try{if(!req.file)return res.status(400).json({error:'Image file required'});if(!['body','garment'].includes(req.body.type))throw new Error('Image type must be body or garment.');const u=await user(req),url=localUpload(req.file);const {rows:[record]}=await q('INSERT INTO uploads (user_id,type,url) VALUES ($1,$2,$3) RETURNING *',[u.id,req.body.type,url]);res.json({upload_id:record.id,url:record.url});}catch(e){res.status(400).json({error:e.message});}});
app.post('/api/tryon/direct',async(req,res)=>{try{const u=await user(req);const {rows:uploads}=await q('SELECT * FROM uploads WHERE id=ANY($1::uuid[]) AND user_id=$2',[[req.body.body_upload_id,req.body.garment_upload_id],u.id]);const body=uploads.find(x=>x.id===req.body.body_upload_id&&x.type==='body'),garment=uploads.find(x=>x.id===req.body.garment_upload_id&&x.type==='garment');if(!body||!garment)throw new Error('Upload both a body photo and garment image first.');const {rows:[session]}=await q("INSERT INTO sessions (user_id,type,body_upload_id) VALUES ($1,'direct',$2) RETURNING *",[u.id,body.id]);const render=await renderTryOn(body.url,garment.url);const {rows:[snapshot]}=await q("INSERT INTO search_results (session_id,name,source_site,image_url,price,category,batch_number,rank) VALUES ($1,'Your uploaded garment','Personal upload',$2,'', 'garment',1,1) RETURNING *",[session.id,garment.url]);const {rows:[tryon]}=await q('INSERT INTO tryon_results (session_id,search_result_id,body_upload_id,result_image_url,youcam_request_id) VALUES ($1,$2,$3,$4,$5) RETURNING *',[session.id,snapshot.id,body.id,render.result_image_url,render.youcam_request_id]);res.json({session_id:session.id,result:mapResult({...tryon,tryon_id:tryon.id,search_id:snapshot.id,...snapshot})});}catch(e){res.status(502).json({error:e.message});}});
app.post('/api/session/occasion',async(req,res)=>{try{const u=await user(req);const {rows:[body]}=await q("SELECT * FROM uploads WHERE id=$1 AND user_id=$2 AND type='body'",[req.body.body_upload_id,u.id]);if(!body)throw new Error('Upload a body photo first.');const gender=['woman','man','nonbinary','prefer_not_to_say'].includes(req.body.gender)?req.body.gender:'prefer_not_to_say';const {rows:[s]}=await q("INSERT INTO sessions (user_id,type,occasion_text,description_text,gender,body_upload_id) VALUES ($1,'occasion',$2,$3,$4,$5) RETURNING *",[u.id,req.body.occasion_text||'',req.body.description_text||'',gender,body.id]);const results=await createBatch(s);res.json({session_id:s.id,results});}catch(e){res.status(502).json({error:e.message});}});
app.get('/api/session/:id/results',async(req,res)=>{try{const u=await user(req);await sessionFor(req.params.id,u.id);const results=await resultRows(req.params.id);res.json({session_id:req.params.id,results});}catch(e){res.status(404).json({error:e.message});}});
app.post('/api/session/:id/chat',async(req,res)=>{try{const u=await user(req),message=req.body.message?.trim();if(!message)throw new Error('Write a refinement first.');const s=await sessionFor(req.params.id,u.id);const {rows:catalog}=await q('SELECT * FROM search_results WHERE session_id IS NULL ORDER BY rank');const stylist=await refineOutfitRequest({message,occasion:s.occasion_text,description:s.description_text,gender:s.gender,catalog});const {rows:[next]}=await q('SELECT COALESCE(MAX(batch_number),0)+1 AS batch FROM search_results WHERE session_id=$1',[s.id]);const {rows:[count]}=await q('SELECT COUNT(*)::int count FROM tryon_results WHERE session_id=$1',[s.id]);await q("INSERT INTO chat_messages (session_id,role,content,resulting_batch_number) VALUES ($1,'user',$2,$3),($1,'assistant',$4,$3)",[s.id,message,next.batch,stylist.reply]);void (async()=>{try{await createBatch(s,`${message} ${stylist.searchTerms}`);}catch(error){console.error(`Chat VTO batch failed for ${s.id}:`,error.message);await q("INSERT INTO chat_messages (session_id,role,content,resulting_batch_number) VALUES ($1,'assistant',$2,$3)",[s.id,`I understood your request, but the try-on images could not be rendered: ${error.message}`,next.batch]);}})();res.json({assistant_message:stylist.reply,pending:true,expected_batch_number:next.batch,existing_result_count:count.count});}catch(e){res.status(502).json({error:e.message});}});
app.get('/api/history',async(req,res)=>{try{const u=await user(req);const {rows:sessions}=await q('SELECT * FROM sessions WHERE user_id=$1 ORDER BY created_at DESC',[u.id]);for(const s of sessions)s.results=await resultRows(s.id);res.json({sessions});}catch(e){res.status(500).json({error:e.message});}});
app.listen(process.env.PORT||8787,()=>console.log(`Wearwise API listening on ${process.env.PORT||8787} with PostgreSQL persistence`));
