import fs from 'fs/promises';
import path from 'path';
import sharp from 'sharp';

const isConfigured = () => Boolean(process.env.YOUCAM_API_KEY && process.env.YOUCAM_API_BASE_URL && !process.env.YOUCAM_API_KEY.startsWith('replace_'));
const baseUrl = () => process.env.YOUCAM_API_BASE_URL.replace(/\/$/, '');
async function youcamFetch(endpoint, init = {}) { const response = await fetch(`${baseUrl()}${endpoint}`, { ...init, headers: { Authorization: `Bearer ${process.env.YOUCAM_API_KEY}`, 'Content-Type': 'application/json', ...init.headers } }); const raw = await response.text(); let envelope; try { envelope = JSON.parse(raw); } catch { throw new Error(`YouCam returned HTTP ${response.status} with an invalid response.`); } if (!response.ok || envelope.error) throw new Error(envelope.error || `YouCam request failed (HTTP ${response.status}).`); return envelope.data; }
async function readImage(imageUrl) { if (imageUrl.startsWith('/uploads/')) { const filename = path.basename(imageUrl); const bytes = await fs.readFile(path.join(process.cwd(), 'server', 'uploads', filename)); const extension = path.extname(filename).toLowerCase(); return { bytes, name: filename, type: extension === '.png' ? 'image/png' : 'image/jpeg' }; } const response = await fetch(imageUrl); if (!response.ok) throw new Error(`Could not download garment image (HTTP ${response.status}).`); const type = response.headers.get('content-type')?.split(';')[0] || 'image/jpeg'; const bytes = Buffer.from(await response.arrayBuffer()); if (['image/jpeg','image/png'].includes(type)) return { bytes, name: 'garment.jpg', type }; try { const jpeg = await sharp(bytes).jpeg({ quality: 92 }).toBuffer(); return { bytes: jpeg, name: 'garment.jpg', type: 'image/jpeg' }; } catch { throw new Error(`Could not convert the shopping product image (${type}) into a YouCam-compatible JPEG.`); } }
async function uploadToYouCam(imageUrl) { const image = await readImage(imageUrl); if (image.bytes.byteLength > 10 * 1024 * 1024) throw new Error('YouCam accepts images up to 10 MB.'); const data = await youcamFetch('/s2s/v2.0/file/cloth-v3', { method: 'POST', body: JSON.stringify({ files: [{ content_type: image.type, file_name: image.name, file_size: image.bytes.byteLength }] }) }); const uploaded = data.files?.[0]; const request = uploaded?.requests?.[0]; if (!uploaded?.file_id || !request?.url) throw new Error('YouCam did not return an image upload destination.'); const put = await fetch(request.url, { method: request.method || 'PUT', headers: request.headers, body: image.bytes }); if (!put.ok) throw new Error(`Could not upload image to YouCam (HTTP ${put.status}).`); return uploaded.file_id; }
async function pollTask(taskId) { for (let attempt = 0; attempt < 25; attempt += 1) { const task = await youcamFetch(`/s2s/v2.0/task/cloth-v3/${encodeURIComponent(taskId)}`); if (task.task_status === 'success') return task.results; if (task.task_status === 'error') throw new Error(task.error || 'YouCam could not create this try-on.'); await new Promise(resolve => setTimeout(resolve, 1500)); } throw new Error('YouCam is taking too long. Please try again with clearer images.'); }
export async function renderTryOn(bodyUrl, garmentUrl) { if (!isConfigured()) throw new Error('YouCam is not configured. Add YOUCAM_API_KEY and YOUCAM_API_BASE_URL to .env.'); const [src_file_id, ref_file_id] = await Promise.all([uploadToYouCam(bodyUrl), uploadToYouCam(garmentUrl)]); const task = await youcamFetch('/s2s/v2.0/task/cloth-v3', { method: 'POST', body: JSON.stringify({ src_file_id, ref_file_id, garment_category: 'auto' }) }); if (!task.task_id) throw new Error('YouCam did not return a virtual try-on task ID.'); const result = await pollTask(task.task_id); const resultImageUrl = result?.url || result?.results?.url; if (!resultImageUrl) throw new Error('YouCam completed the request without a rendered image.'); return { result_image_url: resultImageUrl, youcam_request_id: task.task_id }; }
export async function renderBatch(bodyUrl, garments, onProgress) { const out = []; for (let i = 0; i < garments.length; i += 3) { const set = await Promise.all(garments.slice(i, i + 3).map(async (garment, index) => { const value = await renderTryOn(bodyUrl, garment.image_url); onProgress?.(i + index, value); return value; })); out.push(...set); } return out; }
